
# tap repositories and their packages

tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/brewdler'
tap 'peco/peco'
tap 'pivotal/tap'

tap 'sanemat/font'

# cask 'applications
cask 'alfred'
cask 'karabiner'
cask 'seil'
cask 'iterm2'
cask 'bettertouchtool'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'appcleaner'
cask 'atom'
cask 'coteditor'
cask 'marked'
cask 'qlmarkdown'
cask 'sourcetree'

# Other Homebrew 'packages
brew 'ack'
brew 'bison'
brew 'binutils'
brew 'carthage'
brew 'caskroom/cask/brew-cask'
brew 'Caskroom/cask/xquartz'
brew 'cmigemo'
brew 'csshx'
brew 'emacs'
brew 'entr'
brew 'fontconfig'
brew 'fontforge', args: ['--with-python']
brew 'gibo'
brew 'git'
brew 'git-plus'
brew 'gnu-sed'
brew 'gnu-time'
brew 'go'
brew 'heroku-toolbelt'
brew 'htop-osx'
brew 'hub', args: ['HEAD']
brew 'imagemagick'
brew 'jq'
brew 'nkf'
brew 'node'
brew 'openssl'
brew 'pcre'
brew 'peco'
brew 'pkg-config'
brew 'python'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ricty'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'xctool'
brew 'zsh'
