
# tap repositories and their packages

tap 'caskroom/cask'
tap 'homebrew/binary'
tap 'homebrew/brewdler'
tap 'peco/peco'
tap 'pivotal/tap'

tap 'sanemat/font'

# Other Homebrew 'packages
brew 'ack'
brew 'bison'
brew 'carthage'
brew 'caskroom/cask/brew-cask'
brew 'Caskroom/cask/xquartz'
brew 'cmigemo'
brew 'csshx'
brew 'emacs'
brew 'entr'
brew 'fontconfig'
brew 'fontforge', args: ['--with-python']
brew 'ghi'
brew 'gibo'
brew 'git'
brew 'git-plus'
brew 'gnu-sed'
brew 'gnu-time'
brew 'go'
brew 'heroku-toolbelt'
brew 'htop-osx'
brew 'hub', args: ['HEAD']
brew 'imagemagick'
brew 'jq'
brew 'maven'
brew 'memcached'
brew 'mercurial'
brew 'nkf'
brew 'node'
brew 'openssl'
brew 'pcre'
brew 'peco'
brew 'pkg-config'
brew 'python'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ricty'
brew 'ruby-build'
brew 'sbt'
brew 'scala'
brew 'ssh-copy-id'
brew 'terraform'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'wget'
brew 'xctool'
brew 'zsh'

# cask 'applications
cask 'appcleaner'
cask 'appcode'
cask 'atom'
cask 'coteditor'
cask 'disk-inventory-x'
cask 'github'
cask 'google-japanese-ime'
cask 'keyboard-maestro'
cask 'kitematic'
cask 'lyn'
cask 'marked'
cask 'mysqlworkbench'
cask 'seil'
cask 'sequel-pro'
cask 'silverlight'
cask 'sourcetree'
cask 'vagrant'
cask 'virtualbox'
