cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'osx-cross/avr'
tap 'PX4/homebrew-px4'

# AppStore apps

mas '1Password',    id: 443987910
mas 'Bear',         id: 1091189122
mas 'Magnet',	    id: 441258766
mas 'Md Linker',    id: 1289119450
mas 'Reeder3',      id: 880001334
mas 'Tweetbot3',    id: 1384080005

# Apps outside AppStore

cask 'adobe-creative-cloud'
cask 'appcleaner'
cask 'docker'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'jetbrains-toolbox'
cask 'paw'
cask 'reveal'
cask 'sketch'
cask 'sketch-toolbox'
cask 'visual-studio-code'

# brew packages

brew 'ack'
brew 'avrdude'
brew 'avr-gcc'
brew 'bison'
brew 'binutils'
brew 'carthage'
brew 'cvs'
brew 'dfu-programmer'
brew 'emacs', args: ['HEAD', 'use-git-head', 'with-cocoa', 'with-gnutls']
brew 'findutils', args: ['with-default-names']
brew 'fish'
brew 'fzf'
brew 'gcc-arm-none-eabi'
brew 'ghq'
brew 'gibo'
brew 'git'
brew 'gnu-sed'
brew 'gnu-time'
brew 'imagemagick'
brew 'jq'
brew 'nkf'
brew 'node'
brew 'openssl'
brew 'pcre'
brew 'pkg-config'
brew 'python'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'ruby-build'
brew 'tig'
brew 'tmux'
brew 'tree'
brew 'wget'
